#ifndef GENERALTYPE_H
#define GENERALTYPE_H

#include <stdint.h>

#define CATCHCHALLENGER_TYPE_ITEM_LIST_SIZE uint8_t
#define CATCHCHALLENGER_TYPE_ITEM_LIST_SIZE_WAREHOUSE uint16_t
#define CATCHCHALLENGER_TYPE_ITEM uint16_t
#define CATCHCHALLENGER_TYPE_ITEM_QUANTITY uint32_t
#define CATCHCHALLENGER_TYPE_MONSTER_LIST_SIZE uint8_t
#define CATCHCHALLENGER_TYPE_MONSTER_LIST_SIZE_WAREHOUSE uint16_t
#define CATCHCHALLENGER_TYPE_MONSTER uint16_t
#define CATCHCHALLENGER_TYPE_SKILL uint16_t
#define CATCHCHALLENGER_TYPE_BUFF uint8_t
#define CATCHCHALLENGER_TYPE_QUEST uint8_t
#define CATCHCHALLENGER_TYPE_MAPID uint16_t
#define CATCHCHALLENGER_TYPE_TELEPORTERID uint16_t
#define CATCHCHALLENGER_TYPE_BOTID uint8_t
#define COORD_TYPE uint8_t
#define SIMPLIFIED_PLAYER_ID_FOR_MAP uint8_t
#define CLAN_ID_TYPE uint32_t
#define SPEED_TYPE uint8_t
#define ZONE_TYPE uint8_t
#define SHOP_TYPE uint8_t
#define FACTORY_TYPE uint16_t

#ifdef CATCHCHALLENGER_LIMIT_254CONNECTED
#define SIMPLIFIED_PLAYER_INDEX_FOR_CONNECTED uint8_t
#define SIMPLIFIED_PLAYER_INDEX_FOR_CONNECTED_MAX 255
#else
#define SIMPLIFIED_PLAYER_INDEX_FOR_CONNECTED uint16_t
#define SIMPLIFIED_PLAYER_INDEX_FOR_CONNECTED_MAX 65535
#endif

#endif // GENERALTYPE_H
