#ifndef POKECRAFT_GENERALVARIABLE_H
#define POKECRAFT_GENERALVARIABLE_H

#define PROTOCOL_HEADER "pokecraft-0.0.0.1"

#define POKECRAFT_EXTRA_CHECK

/*
#define FAKESOCKETDEBUG
#define PROTOCOLPARSINGINPUTDEBUG
#define PROTOCOLPARSINGDEBUG
#define DEBUG_PROTOCOLPARSING_RAW_NETWORK
*/

/*
 *#define DEBUG_MESSAGE_MAP_TP
#define DEBUG_MESSAGE_MAP
#define DEBUG_MESSAGE_MAP_BORDER
#define DEBUG_MESSAGE_MAP_OBJECT
#define DEBUG_MESSAGE_MAP_RAW
//*/

#define DATAPACK_FILE_REGEX "^[0-9/a-zA-Z\\.\\- _]*[0-9a-zA-Z]\\.[a-z]{3,4}$"

#endif // GENERALVARIABLE_H
