#ifndef CATCHCHALLENGER_GENERALVARIABLE_H
#define CATCHCHALLENGER_GENERALVARIABLE_H

#define PROTOCOL_HEADER "catchchallenger-0.0.0.1"

#define CATCHCHALLENGER_EXTRA_CHECK

/*
#define FAKESOCKETDEBUG
#define PROTOCOLPARSINGINPUTDEBUG
#define PROTOCOLPARSINGDEBUG
#define DEBUG_PROTOCOLPARSING_RAW_NETWORK
//*/

/*
#define DEBUG_MESSAGE_MOVEONTHEMAP
#define DEBUG_MESSAGE_MAP_TP
#define DEBUG_MESSAGE_MAP
#define DEBUG_MESSAGE_MAP_BORDER
#define DEBUG_MESSAGE_MAP_OBJECT
#define DEBUG_MESSAGE_MAP_RAW
#define DEBUG_MESSAGE_MONSTER_LOAD
#define DEBUG_CLIENT_PLANTS
//*/
#define DEBUG_MESSAGE_FIGHT_LOAD

#define CATCHCHALLENGER_MONSTER_LEVEL_MAX 100
#define CATCHCHALLENGER_MONSTER_MAX_WEAR_ON_PLAYER 6
#define CATCHCHALLENGER_MONSTER_WILD_SKILL_NUMBER 5
//32Bits for the monster, 8Bits for the gender, 8Bits for level, 8Bits for the next step
#define CATCHCHALLENGER_MIN_RANDOM_TO_FIGHT 7
//if need more than this size and receive less, bug with the preivous message, reset
#define CATCHCHALLENGER_MIN_PACKET_SIZE 128

#define CATCHCHALLENGER_BOTFIGHT_RANGE 5
#define RANDOM_FLOAT_PART_DIVIDER 10000

#define DATAPACK_FILE_REGEX "^[0-9/a-zA-Z\\.\\- _]*[0-9a-zA-Z]\\.[a-z]{3,4}$"
#define DATAPACK_BASE_PATH_MAP "map/"
#define DATAPACK_BASE_PATH_ZONE "map/zone/"
#define DATAPACK_BASE_PATH_SKIN "skin/fighter/"
#define DATAPACK_BASE_PATH_ANIMATION "animation/"
#define DATAPACK_BASE_PATH_ITEM "items/"
#define DATAPACK_BASE_PATH_PLANTS "plants/"
#define DATAPACK_BASE_PATH_MONSTERS "monsters/"
#define DATAPACK_BASE_PATH_SKILLANIMATION "monsters/skill-animation/"
#define DATAPACK_BASE_PATH_FIGHT "fight/"
#define DATAPACK_BASE_PATH_PLAYER "player/"
#define DATAPACK_BASE_PATH_QUESTS "quests/"
#define DATAPACK_BASE_PATH_CRAFTING "crafting/"
#define DATAPACK_BASE_PATH_SHOP "shop/"

#endif // GENERALVARIABLE_H
