#ifndef GENERALTYPE_H
#define GENERALTYPE_H

#include <stdint.h>

#define CATCHCHALLENGER_TYPE_ITEM_LIST_SIZE uint8_t
#define CATCHCHALLENGER_TYPE_ITEM_LIST_SIZE_WAREHOUSE uint16_t
#define CATCHCHALLENGER_TYPE_ITEM uint16_t
#define CATCHCHALLENGER_TYPE_ITEM_QUANTITY uint32_t
#define CATCHCHALLENGER_TYPE_MONSTER_LIST_SIZE uint8_t
#define CATCHCHALLENGER_TYPE_MONSTER_LIST_SIZE_WAREHOUSE uint16_t
#define CATCHCHALLENGER_TYPE_MONSTER uint16_t
#define CATCHCHALLENGER_TYPE_SKILL uint16_t
#define CATCHCHALLENGER_TYPE_BUFF uint8_t
#define CATCHCHALLENGER_TYPE_QUEST uint8_t

#endif // GENERALTYPE_H
