#ifndef GENERALVARIABLE_H
#define GENERALVARIABLE_H

#define PROTOCOL_HEADER "pokecraft-0.0.0.1"
#define CLIENT_VERSION "0.0.1.0"
#define API_CLIENT_VERSION "0.0.0.97"
#define SERVER_VERSION "0.0.2.97"
#define API_PROTOCOL_VERSION "0.0.0.1"

#define POKECRAFT_EXTRA_CHECK

#endif // GENERALVARIABLE_H
