#ifndef CATCHCHALLENGER_ProtocolVersion_H
#define CATCHCHALLENGER_ProtocolVersion_H

#define PROTOCOL_HEADER_VERSION 0x13
#define PROTOCOL_HEADER_LOGIN {0x9c,0xd6,0x49,0x8d,PROTOCOL_HEADER_VERSION}
#define PROTOCOL_HEADER_GAMESERVER {0x60,0x0c,0xd9,0xbb,PROTOCOL_HEADER_VERSION}
#define PROTOCOL_HEADER_MASTERSERVER {0x88,0x62,0xBC,0xBB,0x67,0x9E,0x3D,0xE7,PROTOCOL_HEADER_VERSION}

#endif // ProtocolVersion
