#ifndef CATCHCHALLENGER_CATCHCHALLENGER_VERSIONPRIVATE_H
#define CATCHCHALLENGER_CATCHCHALLENGER_VERSIONPRIVATE_H

#define CATCHCHALLENGER_VERSION_PRIVATE "4.0.0.0"

#endif // CATCHCHALLENGER_CATCHCHALLENGER_VERSIONPRIVATE_H
