#ifndef CATCHCHALLENGER_CATCHCHALLENGER_VERSIONPRIVATE_H
#define CATCHCHALLENGER_CATCHCHALLENGER_VERSIONPRIVATE_H

#define CATCHCHALLENGER_VERSION_PRIVATE "3.0.0.2"

#endif // CATCHCHALLENGER_CATCHCHALLENGER_VERSIONPRIVATE_H
