#ifndef CATCHCHALLENGER_CATCHCHALLENGER_VERSIONPRIVATE_H
#define CATCHCHALLENGER_CATCHCHALLENGER_VERSIONPRIVATE_H

#define CATCHCHALLENGER_VERSION_PRIVATE "3.0.0.1"

#endif // CATCHCHALLENGER_CATCHCHALLENGER_VERSIONPRIVATE_H
