#!/bin/bash

if [ "${TEMP_PATH}" = "" ]
then
	exit;
fi

/usr/bin/rsync -avrt --delete /home/user/Desktop/CatchChallenger/git/ ${TEMP_PATH}/
mkdir -p ${TEMP_PATH}
cd ${TEMP_PATH}/client

export PATH="/mnt/data/perso/progs/emsdk:/mnt/data/perso/progs/emsdk/fastcomp/emscripten:/mnt/data/perso/progs/emsdk/node/8.9.1_64bit/bin:/usr/bin:/usr/lib/llvm/7/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin:/bin:/opt/bin"
export EMSDK="/mnt/data/perso/progs/emsdk"
export EM_CONFIG="/home/user/.emscripten"
export EMSDK_NODE="/mnt/data/perso/progs/emsdk/node/8.9.1_64bit/bin/node"
/mnt/data/perso/progs/qt/qt-everywhere-5.13.0-wasm/qtbase/bin/qmake
make -j5
em++ -s WASM=1 -s FULL_ES2=1 -s USE_WEBGL2=1 -s NO_EXIT_RUNTIME=0 -s ERROR_ON_UNDEFINED_SYMBOLS=1 --bind -s "BINARYEN_TRAP_MODE='clamp'" -s TOTAL_MEMORY=200015872 -s ASSERTIONS=1 -g -Os -g4 -s WASM=1 -s FULL_ES2=1 -s USE_WEBGL2=1 -s NO_EXIT_RUNTIME=0 -s ERROR_ON_UNDEFINED_SYMBOLS=1 --bind -s "BINARYEN_TRAP_MODE='clamp'" -s ASSERTIONS=2 -s DEMANGLE_SUPPORT=1 -s GL_DEBUG=1 -s ALLOW_MEMORY_GROWTH=1 /mnt/data/perso/progs/qt/qt-everywhere-5.13.0-wasm/qtbase/lib/libqtfreetype.a /mnt/data/perso/progs/qt/qt-everywhere-5.13.0-wasm/qtbase/lib/libqtlibpng.a --source-map-base http://localhost:8000/ -o testOpenGL.js Api_protocol.o Api_protocol_loadchar.o Api_protocol_message.o Api_protocol_query.o Api_protocol_reply.o DatapackClientLoader.o DatapackChecksum.o tiled_compression.o tiled_gidmapper.o tiled_imagelayer.o tiled_isometricrenderer.o tiled_layer.o tiled_map.o tiled_mapobject.o tiled_mapreader.o tiled_maprenderer.o tiled_mapwriter.o tiled_objectgroup.o tiled_orthogonalrenderer.o tiled_properties.o tiled_staggeredrenderer.o tiled_tile.o tiled_tilelayer.o tiled_tileset.o Settings.o TileLayerItem.o ObjectGroupItem.o MapVisualiserPlayer.o MapVisualiser.o MapVisualiser-map.o MapObjectItem.o MapItem.o MapVisualiserThread.o MapVisualiserOrder.o PreparedLayer.o MapMark.o MapDoor.o MapControllerMP.o MapControllerMPAPI.o MapControllerMPMove.o MapController.o TriggerAnimation.o TemporaryTile.o PathFinding.o BaseWindow.o BaseWindowMap.o BaseWindowBot.o BaseWindowSelection.o BaseWindowCharacter.o BaseWindowCity.o BaseWindowClan.o BaseWindowFactory.o BaseWindowLoad.o BaseWindowMarket.o BaseWindowOptions.o BaseWindowShop.o BaseWindowWarehouse.o ListEntryEnvolued.o Chat.o WithAnotherPlayer.o GetPrice.o NewProfile.o NewGame.o MapControllerCrafting.o CraftingAnimation.o DatapackClientLoaderCrafting.o BaseWindowCrafting.o QmlMonsterGeneralInformations.o EvolutionControl.o \
DatapackClientLoaderFight.o BaseWindowFight.o BaseWindowFightNextAction.o ClientFightEngine.o MapVisualiserPlayerWithFight.o AnimationControl.o QtDatapackClientLoader.o QtDatapackChecksum.o Api_client_virtual.o Options.o LanguagesSelect.o InternetUpdater.o ExtraSocket.o LocalListener.o CachedString.o Map_client.o FacilityLibClient.o Api_protocol_Qt.o Ultimate.o LoadingScreen.o CCBackground.o CustomButton.o CCWidget.o CCprogressbar.o ScreenTransition.o GameLoader.o GameLoaderThread.o MainScreen.o CCTitle.o OptionsDialog.o Solo.o Multi.o Login.o AddServer.o AskKey.o ConnexionManager.o tinyxml2.o tinyxml2b.o tinyxml2c.o ChatParsing.o ProtocolParsingGeneral.o ProtocolParsingInput.o ProtocolParsingOutput.o ProtocolParsingCheck.o MoveOnTheMap.o Map_loader.o Map_loaderMain.o FacilityLib.o FacilityLibGeneral.o DatapackGeneralLoader.o DatapackGeneralLoaderCrafting.o DatapackGeneralLoaderIndustry.o DatapackGeneralLoaderItem.o DatapackGeneralLoaderMap.o DatapackGeneralLoaderMonsterDrop.o DatapackGeneralLoaderPlant.o DatapackGeneralLoaderQuest.o DatapackGeneralLoaderReputation.o cpp11addition.o cpp11additionstringtointcpp.o cpp11additionstringtointc.o FightLoader.o FightLoaderBuff.o FightLoaderFight.o FightLoaderMonster.o FightLoaderSkill.o CommonMap.o CommonDatapack.o CommonDatapackServerSpec.o CommonSettingsCommon.o CommonSettingsServer.o CommonFightEngine.o CommonFightEngineEnd.o CommonFightEngineTurn.o CommonFightEngineBuff.o CommonFightEngineSkill.o CommonFightEngineWild.o CommonFightEngineBase.o Version.o FeedNews.o Api_client_real.o Api_client_real_base.o Api_client_real_main.o Api_client_real_sub.o QZstdDecodeThread.o BlacklistPassword.o SslCert.o TarDecode.o ZstdDecode.o main.o MapControllerV.o ConnectedSocket.o \
testopengl.js_plugin_import.o qrc_client-resources.o qrc_client-resources-plant.o qrc_client-resources-fight.o qrc_client-resources-multi.o qrc_resources.o moc_MapVisualiserPlayer.o moc_MapVisualiser.o moc_MapItem.o moc_PreparedLayer.o moc_MapMark.o moc_MapVisualiserThread.o moc_MapDoor.o moc_MapControllerMP.o moc_MapController.o moc_TriggerAnimation.o moc_TemporaryTile.o moc_PathFinding.o moc_BaseWindow.o moc_ListEntryEnvolued.o moc_Chat.o moc_WithAnotherPlayer.o moc_GetPrice.o moc_NewProfile.o moc_NewGame.o moc_CraftingAnimation.o moc_QmlMonsterGeneralInformations.o moc_EvolutionControl.o moc_ClientFightEngine.o moc_MapVisualiserPlayerWithFight.o moc_AnimationControl.o moc_QtDatapackClientLoader.o moc_QtDatapackChecksum.o moc_Api_protocol_Qt.o moc_LanguagesSelect.o moc_InternetUpdater.o moc_LocalListener.o moc_Options.o moc_LoadingScreen.o moc_ScreenTransition.o moc_GameLoader.o moc_GameLoaderThread.o moc_MainScreen.o moc_OptionsDialog.o moc_Solo.o moc_Multi.o moc_Login.o moc_AddServer.o moc_AskKey.o moc_ConnexionManager.o moc_FeedNews.o moc_Api_client_real.o moc_QZstdDecodeThread.o moc_SslCert.o moc_MapControllerV.o moc_ConnectedSocket.o   /mnt/data/perso/progs/qt/qt-everywhere-5.13.0-wasm/qtbase/plugins/platforms/libqwasm.a /mnt/data/perso/progs/qt/qt-everywhere-5.13.0-wasm/qtbase/lib/libQt5EventDispatcherSupport.a /mnt/data/perso/progs/qt/qt-everywhere-5.13.0-wasm/qtbase/lib/libQt5FontDatabaseSupport.a /mnt/data/perso/progs/qt/qt-everywhere-5.13.0-wasm/qtbase/lib/libqtfreetype.a /mnt/data/perso/progs/qt/qt-everywhere-5.13.0-wasm/qtbase/lib/libQt5EglSupport.a /mnt/data/perso/progs/qt/qt-everywhere-5.13.0-wasm/qtbase/plugins/imageformats/libqgif.a /mnt/data/perso/progs/qt/qt-everywhere-5.13.0-wasm/qtbase/plugins/imageformats/libqicns.a \
/mnt/data/perso/progs/qt/qt-everywhere-5.13.0-wasm/qtbase/plugins/imageformats/libqico.a /mnt/data/perso/progs/qt/qt-everywhere-5.13.0-wasm/qtbase/plugins/imageformats/libqjpeg.a /mnt/data/perso/progs/qt/qt-everywhere-5.13.0-wasm/qtbase/plugins/imageformats/libqtga.a /mnt/data/perso/progs/qt/qt-everywhere-5.13.0-wasm/qtbase/plugins/imageformats/libqtiff.a /mnt/data/perso/progs/qt/qt-everywhere-5.13.0-wasm/qtbase/plugins/imageformats/libqwbmp.a /mnt/data/perso/progs/qt/qt-everywhere-5.13.0-wasm/qtbase/plugins/imageformats/libqwebp.a /mnt/data/perso/progs/qt/qt-everywhere-5.13.0-wasm/qtbase/lib/libQt5Quick.a /mnt/data/perso/progs/qt/qt-everywhere-5.13.0-wasm/qtbase/lib/libQt5Qml.a /mnt/data/perso/progs/qt/qt-everywhere-5.13.0-wasm/qtbase/lib/libQt5WebSockets.a /mnt/data/perso/progs/qt/qt-everywhere-5.13.0-wasm/qtbase/lib/libQt5OpenGL.a /mnt/data/perso/progs/qt/qt-everywhere-5.13.0-wasm/qtbase/lib/libQt5Widgets.a /mnt/data/perso/progs/qt/qt-everywhere-5.13.0-wasm/qtbase/lib/libQt5Gui.a /mnt/data/perso/progs/qt/qt-everywhere-5.13.0-wasm/qtbase/lib/libqtlibpng.a /mnt/data/perso/progs/qt/qt-everywhere-5.13.0-wasm/qtbase/lib/libqtharfbuzz.a /mnt/data/perso/progs/qt/qt-everywhere-5.13.0-wasm/qtbase/lib/libQt5Network.a /mnt/data/perso/progs/qt/qt-everywhere-5.13.0-wasm/qtbase/lib/libQt5Xml.a /mnt/data/perso/progs/qt/qt-everywhere-5.13.0-wasm/qtbase/lib/libQt5Core.a /mnt/data/perso/progs/qt/qt-everywhere-5.13.0-wasm/qtbase/lib/libqtpcre2.a /mnt/data/perso/progs/qt/qt-everywhere-5.13.0-wasm/qtbase/lib/libzstd.so
