#!/bin/bash
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Tileset /Tileset-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/ 1.tsx/-1.tsx/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/ 2.tsx/-2.tsx/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/ 2.png/-2.png/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/ 1.png/-1.png/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Kanto R/Kanto-R/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Kanto T/Kanto-T/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/(d)/-d/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/(1)/-1/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/(2)/-2/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/(3)/-3/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/(4)/-4/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/(5)/-5/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/(6)/-6/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/(7)/-7/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/(8)/-8/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i 's/.PNG"/.png"/g' {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Sinnoh /Sinnoh-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Land /Land-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Sea /Sea-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Pokemon /Pokemon-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Mansion /Mansion-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/and /and-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Safari /Safari-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Daycare /Daycare-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Hoenn /Hoenn-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Interior - /Interior-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Cycling /Cycling-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Road /Road-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Pokecenter /Pokecenter-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Phoenac /Phoenac-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Orre /Orre-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Poke /Poke-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Victory /Victory-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Ladder /Ladder-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Cave /Cave-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Indigo /Indigo-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Plateau /Plateau-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Cinnabar /Cinnabar-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Lab /Lab-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Violet /Violet-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Ruin /Ruin-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Of /Of-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Alph /Alph-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Olivine /Olivine-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Interior /Interior-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Set /Set-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Gyms /Gyms-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Gym /Gym-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Oreburgh /Oreburgh-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Realgam /Realgam-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Tower /Tower-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Fire /Fire-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Red /Red-/g" {} \;

/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Tileset /Tileset-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/ 1.tsx/-1.tsx/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/ 2.tsx/-2.tsx/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/ 2.png/-2.png/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/ 1.png/-1.png/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Kanto R/Kanto-R/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Kanto T/Kanto-T/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/(d)/-d/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/(1)/-1/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/(2)/-2/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/(3)/-3/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/(4)/-4/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/(5)/-5/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/(6)/-6/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/(7)/-7/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/(8)/-8/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Sinnoh /Sinnoh-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Land /Land-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Sea /Sea-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Pokemon /Pokemon-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Mansion /Mansion-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/and /and-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Safari /Safari-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Daycare /Daycare-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Hoenn /Hoenn-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Interior - /Interior-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Cycling /Cycling-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Road /Road-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Pokecenter /Pokecenter-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Phoenac /Phoenac-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Orre /Orre-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Poke /Poke-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Victory /Victory-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Ladder /Ladder-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Cave /Cave-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Indigo /Indigo-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Plateau /Plateau-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Cinnabar /Cinnabar-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Lab /Lab-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Violet /Violet-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Ruin /Ruin-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Of /Of-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Alph /Alph-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Olivine /Olivine-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Interior /Interior-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Set /Set-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Gyms /Gyms-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Gym /Gym-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Oreburgh /Oreburgh-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Realgam /Realgam-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Tower /Tower-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Fire /Fire-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Red /Red-/g" {} \;