#!/bin/bash
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Tileset /Tileset-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/ 1.tsx/-1.tsx/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/ 2.tsx/-2.tsx/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/ 2.png/-2.png/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/ 1.png/-1.png/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Kanto R/Kanto-R/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Kanto T/Kanto-T/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/(d)/-d/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/(1)/-1/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/(2)/-2/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/(3)/-3/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/(4)/-4/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/(5)/-5/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/(6)/-6/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/(7)/-7/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/(8)/-8/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i 's/.PNG"/.png"/g' {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tsx' -exec sed -i "s/Sinnoh /Sinnoh-/g" {} \;

/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Tileset /Tileset-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/ 1.tsx/-1.tsx/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/ 2.tsx/-2.tsx/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/ 2.png/-2.png/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/ 1.png/-1.png/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Kanto R/Kanto-R/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Kanto T/Kanto-T/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/(d)/-d/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/(1)/-1/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/(2)/-2/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/(3)/-3/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/(4)/-4/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/(5)/-5/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/(6)/-6/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/(7)/-7/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/(8)/-8/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/Sinnoh /Sinnoh-/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/LedgesDown/LedgesBottom/g" {} \;
/usr/bin/nice -n 19 /usr/bin/ionice -c 3 /usr/bin/find ./ -type f -name '*.tmx' -exec sed -i "s/LedgesUp/LedgesTop/g" {} \;
