import threading
import subprocess
import os
import sys
import multiprocessing
import logging

iterator = -1
logging.basicConfig(level=logging.DEBUG, format='(%(threadName)-9s) %(message)s',)

class Requester(threading.Thread):
    def __init__(self):
        threading.Thread.__init__(self)
        self.lock = threading.Lock()

    def run(self):
        global iterator, content, length
        while True:
            self.lock.acquire()
            iterator = iterator + 1
            if iterator < length:
                command = content[iterator]
            else:
                command = None
            self.lock.release()
            if command is None:
                break
            elif len(command) > 0:
                parts = command.strip().split(' ')
                try:
                    output = subprocess.run(parts, stdout=subprocess.PIPE, check=True)
                    if output.returncode != 0:
                        logging.error(output.stderr)
                except Exception as err:
                    logging.error('command: ' + command + ' exception: ' + str(err))

content = """
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o sha224.o ../../general/sha224/sha224.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o main-epoll-login-master.o ../master/main-epoll-login-master.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o EpollClientLoginMaster.o ../master/EpollClientLoginMaster.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o EpollServerLoginMaster.o ../master/EpollServerLoginMaster.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o EpollClientLoginMasterStaticVar.o ../master/EpollClientLoginMasterStaticVar.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o EpollClientLoginMasterProtocolParsing.o ../master/EpollClientLoginMasterProtocolParsing.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o CharactersGroup.o ../master/CharactersGroup.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o PlayerUpdaterToLogin.o ../master/PlayerUpdaterToLogin.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o PurgeTheLockedAccount.o ../master/PurgeTheLockedAccount.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o CheckTimeoutGameServer.o ../master/CheckTimeoutGameServer.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o AutomaticPingSend.o ../master/AutomaticPingSend.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o TimeRangeEvent.o ../master/TimeRangeEvent.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o EpollTimer.o ../epoll/EpollTimer.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o Epoll.o ../epoll/Epoll.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o EpollGenericSslServer.o ../epoll/EpollGenericSslServer.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o EpollGenericServer.o ../epoll/EpollGenericServer.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o EpollClient.o ../epoll/EpollClient.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o EpollSocket.o ../epoll/EpollSocket.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o EpollSslClient.o ../epoll/EpollSslClient.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o EpollPostgresql.o ../epoll/db/EpollPostgresql.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o ProtocolParsingCheck.o ../../general/base/ProtocolParsingCheck.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o ProtocolParsingGeneral.o ../../general/base/ProtocolParsingGeneral.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o ProtocolParsingInput.o ../../general/base/ProtocolParsingInput.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o ProtocolParsingOutput.o ../../general/base/ProtocolParsingOutput.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o FacilityLibGeneral.o ../../general/base/FacilityLibGeneral.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o CommonDatapack.o ../../general/base/CommonDatapack.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o DatapackGeneralLoader.o ../../general/base/DatapackGeneralLoader.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o DatapackGeneralLoaderCrafting.o ../../general/base/DatapackGeneralLoaderCrafting.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o DatapackGeneralLoaderIndustry.o ../../general/base/DatapackGeneralLoaderIndustry.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o DatapackGeneralLoaderItem.o ../../general/base/DatapackGeneralLoaderItem.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o DatapackGeneralLoaderMap.o ../../general/base/DatapackGeneralLoaderMap.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o DatapackGeneralLoaderMonsterDrop.o ../../general/base/DatapackGeneralLoaderMonsterDrop.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o DatapackGeneralLoaderPlant.o ../../general/base/DatapackGeneralLoaderPlant.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o DatapackGeneralLoaderQuest.o ../../general/base/DatapackGeneralLoaderQuest.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o DatapackGeneralLoaderReputation.o ../../general/base/DatapackGeneralLoaderReputation.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o CommonFightEngineBase.o ../../general/fight/CommonFightEngineBase.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o FightLoader.o ../../general/fight/FightLoader.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o FightLoaderBuff.o ../../general/fight/FightLoaderBuff.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o FightLoaderFight.o ../../general/fight/FightLoaderFight.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o FightLoaderMonster.o ../../general/fight/FightLoaderMonster.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o FightLoaderSkill.o ../../general/fight/FightLoaderSkill.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o CommonSettingsCommon.o ../../general/base/CommonSettingsCommon.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o cpp11addition.o ../../general/base/cpp11addition.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o cpp11additionstringtointc.o ../../general/base/cpp11additionstringtointc.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o cpp11additionstringtointcpp.o ../../general/base/cpp11additionstringtointcpp.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o BaseServerMasterLoadDictionary.o ../base/BaseServerMasterLoadDictionary.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o DatabaseBase.o ../base/DatabaseBase.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o BaseServerMasterSendDatapack.o ../base/BaseServerMasterSendDatapack.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o DatabaseFunction.o ../base/DatabaseFunction.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o SqlFunction.o ../base/SqlFunction.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o TinyXMLSettings.o ../base/TinyXMLSettings.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o Version.o ../../general/base/Version.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o tinyxml2.o ../../general/base/tinyXML2/tinyxml2.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o tinyxml2b.o ../../general/base/tinyXML2/tinyxml2b.cpp
clang++ -c -pipe -flto=thin -fstack-protector-all -std=c++0x -g -O2 -fno-rtti -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DEPOLLCATCHCHALLENGERSERVERNOGAMESERVER -DCATCHCHALLENGER_CLASS_MASTER -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_QML_DEBUG -I../master -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o tinyxml2c.o ../../general/base/tinyXML2/tinyxml2c.cpp
"""
content = content.strip().split('\n')

MAX_CONCURRENCE = multiprocessing.cpu_count()+1

length = len(content)
for i in range(MAX_CONCURRENCE):
    t = Requester()
    t.start()

main_thread = threading.currentThread()
for t in threading.enumerate():
    if t is not main_thread:
        t.join()

os.system("clang++ -fuse-ld=lld -flto=thin -Wl,--thinlto-jobs="+str(multiprocessing.cpu_count()+1)+" -O2 -ccc-gcc-name g++ -o catchchallenger-server-master sha224.o main-epoll-login-master.o EpollClientLoginMaster.o EpollServerLoginMaster.o EpollClientLoginMasterStaticVar.o EpollClientLoginMasterProtocolParsing.o CharactersGroup.o PlayerUpdaterToLogin.o PurgeTheLockedAccount.o CheckTimeoutGameServer.o AutomaticPingSend.o TimeRangeEvent.o EpollTimer.o Epoll.o EpollGenericSslServer.o EpollGenericServer.o EpollClient.o EpollSocket.o EpollSslClient.o EpollPostgresql.o ProtocolParsingCheck.o ProtocolParsingGeneral.o ProtocolParsingInput.o ProtocolParsingOutput.o FacilityLibGeneral.o CommonDatapack.o DatapackGeneralLoader.o DatapackGeneralLoaderCrafting.o DatapackGeneralLoaderIndustry.o DatapackGeneralLoaderItem.o DatapackGeneralLoaderMap.o DatapackGeneralLoaderMonsterDrop.o DatapackGeneralLoaderPlant.o DatapackGeneralLoaderQuest.o DatapackGeneralLoaderReputation.o CommonFightEngineBase.o FightLoader.o FightLoaderBuff.o FightLoaderFight.o FightLoaderMonster.o FightLoaderSkill.o CommonSettingsCommon.o cpp11addition.o cpp11additionstringtointc.o cpp11additionstringtointcpp.o BaseServerMasterLoadDictionary.o DatabaseBase.o BaseServerMasterSendDatapack.o DatabaseFunction.o SqlFunction.o TinyXMLSettings.o Version.o tinyxml2.o tinyxml2b.o tinyxml2c.o -lpq")
print('Finished')
