import threading
import subprocess
import os
import sys
import multiprocessing
import logging

iterator = -1
logging.basicConfig(level=logging.DEBUG, format='(%(threadName)-9s) %(message)s',)
has_success = True

class Requester(threading.Thread):
    def __init__(self):
        threading.Thread.__init__(self)
        self.lock = threading.Lock()

    def run(self):
        global iterator, content, length
        while True:
            self.lock.acquire()
            iterator = iterator + 1
            if iterator < length:
                command = content[iterator]
            else:
                command = None
            self.lock.release()
            if command is None:
                break
            elif len(command) > 0:
                parts = command.strip().split(' ')
                try:
                    output = subprocess.run(parts, stdout=subprocess.PIPE, check=True)
                    if output.returncode != 0:
                        logging.error(output.stderr)
                except Exception as err:
                    logging.error('command: ' + command + ' exception: ' + str(err))

content = """
clang++ -c -std=c++0x -g -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -Walloca -Wcast-qual -Wconversion -Wformat=2 -Wformat-security -Wnull-dereference -Wstack-protector -Wvla -Warray-bounds -Warray-bounds-pointer-arithmetic -Wassign-enum -Wbad-function-cast -Wconditional-uninitialized -Wconversion -Wfloat-equal -Wformat-type-confusion -Widiomatic-parentheses -Wimplicit-fallthrough -Wloop-analysis -Wpointer-arith -Wshift-sign-overflow -Wshorten-64-to-32 -Wswitch-enum -Wtautological-constant-in-range-compare -Wunreachable-code-aggressive -Wthread-safety -Wthread-safety-beta -Wcomma -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fsanitize=safe-stack -fPIE -fstack-clash-protection -DEPOLLCATCHCHALLENGERSERVER -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DSERVERNOBUFFER -DCATCHCHALLENGER_CLASS_STATS -DNOWEBSOCKET -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -I../stats -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang++ -o main.o ../stats/main.cpp
clang++ -c -std=c++0x -g -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -Walloca -Wcast-qual -Wconversion -Wformat=2 -Wformat-security -Wnull-dereference -Wstack-protector -Wvla -Warray-bounds -Warray-bounds-pointer-arithmetic -Wassign-enum -Wbad-function-cast -Wconditional-uninitialized -Wconversion -Wfloat-equal -Wformat-type-confusion -Widiomatic-parentheses -Wimplicit-fallthrough -Wloop-analysis -Wpointer-arith -Wshift-sign-overflow -Wshorten-64-to-32 -Wswitch-enum -Wtautological-constant-in-range-compare -Wunreachable-code-aggressive -Wthread-safety -Wthread-safety-beta -Wcomma -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fsanitize=safe-stack -fPIE -fstack-clash-protection -DEPOLLCATCHCHALLENGERSERVER -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DSERVERNOBUFFER -DCATCHCHALLENGER_CLASS_STATS -DNOWEBSOCKET -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -I../stats -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang++ -o sha224.o ../../general/sha224/sha224.cpp
clang++ -c -std=c++0x -g -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -Walloca -Wcast-qual -Wconversion -Wformat=2 -Wformat-security -Wnull-dereference -Wstack-protector -Wvla -Warray-bounds -Warray-bounds-pointer-arithmetic -Wassign-enum -Wbad-function-cast -Wconditional-uninitialized -Wconversion -Wfloat-equal -Wformat-type-confusion -Widiomatic-parentheses -Wimplicit-fallthrough -Wloop-analysis -Wpointer-arith -Wshift-sign-overflow -Wshorten-64-to-32 -Wswitch-enum -Wtautological-constant-in-range-compare -Wunreachable-code-aggressive -Wthread-safety -Wthread-safety-beta -Wcomma -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fsanitize=safe-stack -fPIE -fstack-clash-protection -DEPOLLCATCHCHALLENGERSERVER -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DSERVERNOBUFFER -DCATCHCHALLENGER_CLASS_STATS -DNOWEBSOCKET -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -I../stats -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang++ -o LinkToLogin.o ../stats/LinkToLogin.cpp
clang++ -c -std=c++0x -g -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -Walloca -Wcast-qual -Wconversion -Wformat=2 -Wformat-security -Wnull-dereference -Wstack-protector -Wvla -Warray-bounds -Warray-bounds-pointer-arithmetic -Wassign-enum -Wbad-function-cast -Wconditional-uninitialized -Wconversion -Wfloat-equal -Wformat-type-confusion -Widiomatic-parentheses -Wimplicit-fallthrough -Wloop-analysis -Wpointer-arith -Wshift-sign-overflow -Wshorten-64-to-32 -Wswitch-enum -Wtautological-constant-in-range-compare -Wunreachable-code-aggressive -Wthread-safety -Wthread-safety-beta -Wcomma -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fsanitize=safe-stack -fPIE -fstack-clash-protection -DEPOLLCATCHCHALLENGERSERVER -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DSERVERNOBUFFER -DCATCHCHALLENGER_CLASS_STATS -DNOWEBSOCKET -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -I../stats -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang++ -o LinkToLoginProtocolParsing.o ../stats/LinkToLoginProtocolParsing.cpp
clang++ -c -std=c++0x -g -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -Walloca -Wcast-qual -Wconversion -Wformat=2 -Wformat-security -Wnull-dereference -Wstack-protector -Wvla -Warray-bounds -Warray-bounds-pointer-arithmetic -Wassign-enum -Wbad-function-cast -Wconditional-uninitialized -Wconversion -Wfloat-equal -Wformat-type-confusion -Widiomatic-parentheses -Wimplicit-fallthrough -Wloop-analysis -Wpointer-arith -Wshift-sign-overflow -Wshorten-64-to-32 -Wswitch-enum -Wtautological-constant-in-range-compare -Wunreachable-code-aggressive -Wthread-safety -Wthread-safety-beta -Wcomma -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fsanitize=safe-stack -fPIE -fstack-clash-protection -DEPOLLCATCHCHALLENGERSERVER -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DSERVERNOBUFFER -DCATCHCHALLENGER_CLASS_STATS -DNOWEBSOCKET -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -I../stats -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang++ -o LinkToLoginStaticVar.o ../stats/LinkToLoginStaticVar.cpp
clang++ -c -std=c++0x -g -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -Walloca -Wcast-qual -Wconversion -Wformat=2 -Wformat-security -Wnull-dereference -Wstack-protector -Wvla -Warray-bounds -Warray-bounds-pointer-arithmetic -Wassign-enum -Wbad-function-cast -Wconditional-uninitialized -Wconversion -Wfloat-equal -Wformat-type-confusion -Widiomatic-parentheses -Wimplicit-fallthrough -Wloop-analysis -Wpointer-arith -Wshift-sign-overflow -Wshorten-64-to-32 -Wswitch-enum -Wtautological-constant-in-range-compare -Wunreachable-code-aggressive -Wthread-safety -Wthread-safety-beta -Wcomma -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fsanitize=safe-stack -fPIE -fstack-clash-protection -DEPOLLCATCHCHALLENGERSERVER -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DSERVERNOBUFFER -DCATCHCHALLENGER_CLASS_STATS -DNOWEBSOCKET -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -I../stats -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang++ -o Epoll.o ../../server/epoll/Epoll.cpp
clang++ -c -std=c++0x -g -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -Walloca -Wcast-qual -Wconversion -Wformat=2 -Wformat-security -Wnull-dereference -Wstack-protector -Wvla -Warray-bounds -Warray-bounds-pointer-arithmetic -Wassign-enum -Wbad-function-cast -Wconditional-uninitialized -Wconversion -Wfloat-equal -Wformat-type-confusion -Widiomatic-parentheses -Wimplicit-fallthrough -Wloop-analysis -Wpointer-arith -Wshift-sign-overflow -Wshorten-64-to-32 -Wswitch-enum -Wtautological-constant-in-range-compare -Wunreachable-code-aggressive -Wthread-safety -Wthread-safety-beta -Wcomma -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fsanitize=safe-stack -fPIE -fstack-clash-protection -DEPOLLCATCHCHALLENGERSERVER -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DSERVERNOBUFFER -DCATCHCHALLENGER_CLASS_STATS -DNOWEBSOCKET -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -I../stats -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang++ -o EpollSocket.o ../../server/epoll/EpollSocket.cpp
clang++ -c -std=c++0x -g -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -Walloca -Wcast-qual -Wconversion -Wformat=2 -Wformat-security -Wnull-dereference -Wstack-protector -Wvla -Warray-bounds -Warray-bounds-pointer-arithmetic -Wassign-enum -Wbad-function-cast -Wconditional-uninitialized -Wconversion -Wfloat-equal -Wformat-type-confusion -Widiomatic-parentheses -Wimplicit-fallthrough -Wloop-analysis -Wpointer-arith -Wshift-sign-overflow -Wshorten-64-to-32 -Wswitch-enum -Wtautological-constant-in-range-compare -Wunreachable-code-aggressive -Wthread-safety -Wthread-safety-beta -Wcomma -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fsanitize=safe-stack -fPIE -fstack-clash-protection -DEPOLLCATCHCHALLENGERSERVER -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DSERVERNOBUFFER -DCATCHCHALLENGER_CLASS_STATS -DNOWEBSOCKET -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -I../stats -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang++ -o TinyXMLSettings.o ../../server/base/TinyXMLSettings.cpp
clang++ -c -std=c++0x -g -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -Walloca -Wcast-qual -Wconversion -Wformat=2 -Wformat-security -Wnull-dereference -Wstack-protector -Wvla -Warray-bounds -Warray-bounds-pointer-arithmetic -Wassign-enum -Wbad-function-cast -Wconditional-uninitialized -Wconversion -Wfloat-equal -Wformat-type-confusion -Widiomatic-parentheses -Wimplicit-fallthrough -Wloop-analysis -Wpointer-arith -Wshift-sign-overflow -Wshorten-64-to-32 -Wswitch-enum -Wtautological-constant-in-range-compare -Wunreachable-code-aggressive -Wthread-safety -Wthread-safety-beta -Wcomma -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fsanitize=safe-stack -fPIE -fstack-clash-protection -DEPOLLCATCHCHALLENGERSERVER -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DSERVERNOBUFFER -DCATCHCHALLENGER_CLASS_STATS -DNOWEBSOCKET -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -I../stats -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang++ -o FacilityLibGeneral.o ../../general/base/FacilityLibGeneral.cpp
clang++ -c -std=c++0x -g -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -Walloca -Wcast-qual -Wconversion -Wformat=2 -Wformat-security -Wnull-dereference -Wstack-protector -Wvla -Warray-bounds -Warray-bounds-pointer-arithmetic -Wassign-enum -Wbad-function-cast -Wconditional-uninitialized -Wconversion -Wfloat-equal -Wformat-type-confusion -Widiomatic-parentheses -Wimplicit-fallthrough -Wloop-analysis -Wpointer-arith -Wshift-sign-overflow -Wshorten-64-to-32 -Wswitch-enum -Wtautological-constant-in-range-compare -Wunreachable-code-aggressive -Wthread-safety -Wthread-safety-beta -Wcomma -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fsanitize=safe-stack -fPIE -fstack-clash-protection -DEPOLLCATCHCHALLENGERSERVER -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DSERVERNOBUFFER -DCATCHCHALLENGER_CLASS_STATS -DNOWEBSOCKET -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -I../stats -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang++ -o cpp11addition.o ../../general/base/cpp11addition.cpp
clang++ -c -std=c++0x -g -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -Walloca -Wcast-qual -Wconversion -Wformat=2 -Wformat-security -Wnull-dereference -Wstack-protector -Wvla -Warray-bounds -Warray-bounds-pointer-arithmetic -Wassign-enum -Wbad-function-cast -Wconditional-uninitialized -Wconversion -Wfloat-equal -Wformat-type-confusion -Widiomatic-parentheses -Wimplicit-fallthrough -Wloop-analysis -Wpointer-arith -Wshift-sign-overflow -Wshorten-64-to-32 -Wswitch-enum -Wtautological-constant-in-range-compare -Wunreachable-code-aggressive -Wthread-safety -Wthread-safety-beta -Wcomma -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fsanitize=safe-stack -fPIE -fstack-clash-protection -DEPOLLCATCHCHALLENGERSERVER -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DSERVERNOBUFFER -DCATCHCHALLENGER_CLASS_STATS -DNOWEBSOCKET -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -I../stats -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang++ -o cpp11additionstringtointc.o ../../general/base/cpp11additionstringtointc.cpp
clang++ -c -std=c++0x -g -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -Walloca -Wcast-qual -Wconversion -Wformat=2 -Wformat-security -Wnull-dereference -Wstack-protector -Wvla -Warray-bounds -Warray-bounds-pointer-arithmetic -Wassign-enum -Wbad-function-cast -Wconditional-uninitialized -Wconversion -Wfloat-equal -Wformat-type-confusion -Widiomatic-parentheses -Wimplicit-fallthrough -Wloop-analysis -Wpointer-arith -Wshift-sign-overflow -Wshorten-64-to-32 -Wswitch-enum -Wtautological-constant-in-range-compare -Wunreachable-code-aggressive -Wthread-safety -Wthread-safety-beta -Wcomma -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fsanitize=safe-stack -fPIE -fstack-clash-protection -DEPOLLCATCHCHALLENGERSERVER -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DSERVERNOBUFFER -DCATCHCHALLENGER_CLASS_STATS -DNOWEBSOCKET -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -I../stats -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang++ -o cpp11additionstringtointcpp.o ../../general/base/cpp11additionstringtointcpp.cpp
clang++ -c -std=c++0x -g -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -Walloca -Wcast-qual -Wconversion -Wformat=2 -Wformat-security -Wnull-dereference -Wstack-protector -Wvla -Warray-bounds -Warray-bounds-pointer-arithmetic -Wassign-enum -Wbad-function-cast -Wconditional-uninitialized -Wconversion -Wfloat-equal -Wformat-type-confusion -Widiomatic-parentheses -Wimplicit-fallthrough -Wloop-analysis -Wpointer-arith -Wshift-sign-overflow -Wshorten-64-to-32 -Wswitch-enum -Wtautological-constant-in-range-compare -Wunreachable-code-aggressive -Wthread-safety -Wthread-safety-beta -Wcomma -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fsanitize=safe-stack -fPIE -fstack-clash-protection -DEPOLLCATCHCHALLENGERSERVER -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DSERVERNOBUFFER -DCATCHCHALLENGER_CLASS_STATS -DNOWEBSOCKET -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -I../stats -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang++ -o ProtocolParsingCheck.o ../../general/base/ProtocolParsingCheck.cpp
clang++ -c -std=c++0x -g -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -Walloca -Wcast-qual -Wconversion -Wformat=2 -Wformat-security -Wnull-dereference -Wstack-protector -Wvla -Warray-bounds -Warray-bounds-pointer-arithmetic -Wassign-enum -Wbad-function-cast -Wconditional-uninitialized -Wconversion -Wfloat-equal -Wformat-type-confusion -Widiomatic-parentheses -Wimplicit-fallthrough -Wloop-analysis -Wpointer-arith -Wshift-sign-overflow -Wshorten-64-to-32 -Wswitch-enum -Wtautological-constant-in-range-compare -Wunreachable-code-aggressive -Wthread-safety -Wthread-safety-beta -Wcomma -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fsanitize=safe-stack -fPIE -fstack-clash-protection -DEPOLLCATCHCHALLENGERSERVER -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DSERVERNOBUFFER -DCATCHCHALLENGER_CLASS_STATS -DNOWEBSOCKET -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -I../stats -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang++ -o ProtocolParsingGeneral.o ../../general/base/ProtocolParsingGeneral.cpp
clang++ -c -std=c++0x -g -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -Walloca -Wcast-qual -Wconversion -Wformat=2 -Wformat-security -Wnull-dereference -Wstack-protector -Wvla -Warray-bounds -Warray-bounds-pointer-arithmetic -Wassign-enum -Wbad-function-cast -Wconditional-uninitialized -Wconversion -Wfloat-equal -Wformat-type-confusion -Widiomatic-parentheses -Wimplicit-fallthrough -Wloop-analysis -Wpointer-arith -Wshift-sign-overflow -Wshorten-64-to-32 -Wswitch-enum -Wtautological-constant-in-range-compare -Wunreachable-code-aggressive -Wthread-safety -Wthread-safety-beta -Wcomma -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fsanitize=safe-stack -fPIE -fstack-clash-protection -DEPOLLCATCHCHALLENGERSERVER -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DSERVERNOBUFFER -DCATCHCHALLENGER_CLASS_STATS -DNOWEBSOCKET -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -I../stats -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang++ -o ProtocolParsingInput.o ../../general/base/ProtocolParsingInput.cpp
clang++ -c -std=c++0x -g -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -Walloca -Wcast-qual -Wconversion -Wformat=2 -Wformat-security -Wnull-dereference -Wstack-protector -Wvla -Warray-bounds -Warray-bounds-pointer-arithmetic -Wassign-enum -Wbad-function-cast -Wconditional-uninitialized -Wconversion -Wfloat-equal -Wformat-type-confusion -Widiomatic-parentheses -Wimplicit-fallthrough -Wloop-analysis -Wpointer-arith -Wshift-sign-overflow -Wshorten-64-to-32 -Wswitch-enum -Wtautological-constant-in-range-compare -Wunreachable-code-aggressive -Wthread-safety -Wthread-safety-beta -Wcomma -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fsanitize=safe-stack -fPIE -fstack-clash-protection -DEPOLLCATCHCHALLENGERSERVER -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DSERVERNOBUFFER -DCATCHCHALLENGER_CLASS_STATS -DNOWEBSOCKET -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -I../stats -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang++ -o ProtocolParsingOutput.o ../../general/base/ProtocolParsingOutput.cpp
clang++ -c -std=c++0x -g -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -Walloca -Wcast-qual -Wconversion -Wformat=2 -Wformat-security -Wnull-dereference -Wstack-protector -Wvla -Warray-bounds -Warray-bounds-pointer-arithmetic -Wassign-enum -Wbad-function-cast -Wconditional-uninitialized -Wconversion -Wfloat-equal -Wformat-type-confusion -Widiomatic-parentheses -Wimplicit-fallthrough -Wloop-analysis -Wpointer-arith -Wshift-sign-overflow -Wshorten-64-to-32 -Wswitch-enum -Wtautological-constant-in-range-compare -Wunreachable-code-aggressive -Wthread-safety -Wthread-safety-beta -Wcomma -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fsanitize=safe-stack -fPIE -fstack-clash-protection -DEPOLLCATCHCHALLENGERSERVER -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DSERVERNOBUFFER -DCATCHCHALLENGER_CLASS_STATS -DNOWEBSOCKET -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -I../stats -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang++ -o EpollClient.o ../../server/epoll/EpollClient.cpp
clang++ -c -std=c++0x -g -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -Walloca -Wcast-qual -Wconversion -Wformat=2 -Wformat-security -Wnull-dereference -Wstack-protector -Wvla -Warray-bounds -Warray-bounds-pointer-arithmetic -Wassign-enum -Wbad-function-cast -Wconditional-uninitialized -Wconversion -Wfloat-equal -Wformat-type-confusion -Widiomatic-parentheses -Wimplicit-fallthrough -Wloop-analysis -Wpointer-arith -Wshift-sign-overflow -Wshorten-64-to-32 -Wswitch-enum -Wtautological-constant-in-range-compare -Wunreachable-code-aggressive -Wthread-safety -Wthread-safety-beta -Wcomma -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fsanitize=safe-stack -fPIE -fstack-clash-protection -DEPOLLCATCHCHALLENGERSERVER -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DSERVERNOBUFFER -DCATCHCHALLENGER_CLASS_STATS -DNOWEBSOCKET -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -I../stats -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang++ -o EpollUnixSocketServer.o ../../server/epoll/EpollUnixSocketServer.cpp
clang++ -c -std=c++0x -g -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -Walloca -Wcast-qual -Wconversion -Wformat=2 -Wformat-security -Wnull-dereference -Wstack-protector -Wvla -Warray-bounds -Warray-bounds-pointer-arithmetic -Wassign-enum -Wbad-function-cast -Wconditional-uninitialized -Wconversion -Wfloat-equal -Wformat-type-confusion -Widiomatic-parentheses -Wimplicit-fallthrough -Wloop-analysis -Wpointer-arith -Wshift-sign-overflow -Wshorten-64-to-32 -Wswitch-enum -Wtautological-constant-in-range-compare -Wunreachable-code-aggressive -Wthread-safety -Wthread-safety-beta -Wcomma -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fsanitize=safe-stack -fPIE -fstack-clash-protection -DEPOLLCATCHCHALLENGERSERVER -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DSERVERNOBUFFER -DCATCHCHALLENGER_CLASS_STATS -DNOWEBSOCKET -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -I../stats -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang++ -o EpollServerStats.o ../stats/EpollServerStats.cpp
clang++ -c -std=c++0x -g -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -Walloca -Wcast-qual -Wconversion -Wformat=2 -Wformat-security -Wnull-dereference -Wstack-protector -Wvla -Warray-bounds -Warray-bounds-pointer-arithmetic -Wassign-enum -Wbad-function-cast -Wconditional-uninitialized -Wconversion -Wfloat-equal -Wformat-type-confusion -Widiomatic-parentheses -Wimplicit-fallthrough -Wloop-analysis -Wpointer-arith -Wshift-sign-overflow -Wshorten-64-to-32 -Wswitch-enum -Wtautological-constant-in-range-compare -Wunreachable-code-aggressive -Wthread-safety -Wthread-safety-beta -Wcomma -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fsanitize=safe-stack -fPIE -fstack-clash-protection -DEPOLLCATCHCHALLENGERSERVER -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DSERVERNOBUFFER -DCATCHCHALLENGER_CLASS_STATS -DNOWEBSOCKET -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -I../stats -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang++ -o tinyxml2.o ../../general/tinyXML2/tinyxml2.cpp
clang++ -c -std=c++0x -g -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -Walloca -Wcast-qual -Wconversion -Wformat=2 -Wformat-security -Wnull-dereference -Wstack-protector -Wvla -Warray-bounds -Warray-bounds-pointer-arithmetic -Wassign-enum -Wbad-function-cast -Wconditional-uninitialized -Wconversion -Wfloat-equal -Wformat-type-confusion -Widiomatic-parentheses -Wimplicit-fallthrough -Wloop-analysis -Wpointer-arith -Wshift-sign-overflow -Wshorten-64-to-32 -Wswitch-enum -Wtautological-constant-in-range-compare -Wunreachable-code-aggressive -Wthread-safety -Wthread-safety-beta -Wcomma -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fsanitize=safe-stack -fPIE -fstack-clash-protection -DEPOLLCATCHCHALLENGERSERVER -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DSERVERNOBUFFER -DCATCHCHALLENGER_CLASS_STATS -DNOWEBSOCKET -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -I../stats -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang++ -o tinyxml2b.o ../../general/tinyXML2/tinyxml2b.cpp
clang++ -c -std=c++0x -g -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -Walloca -Wcast-qual -Wconversion -Wformat=2 -Wformat-security -Wnull-dereference -Wstack-protector -Wvla -Warray-bounds -Warray-bounds-pointer-arithmetic -Wassign-enum -Wbad-function-cast -Wconditional-uninitialized -Wconversion -Wfloat-equal -Wformat-type-confusion -Widiomatic-parentheses -Wimplicit-fallthrough -Wloop-analysis -Wpointer-arith -Wshift-sign-overflow -Wshorten-64-to-32 -Wswitch-enum -Wtautological-constant-in-range-compare -Wunreachable-code-aggressive -Wthread-safety -Wthread-safety-beta -Wcomma -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fsanitize=safe-stack -fPIE -fstack-clash-protection -DEPOLLCATCHCHALLENGERSERVER -DEPOLLCATCHCHALLENGERSERVERNOCOMPRESSION -DSERVERNOBUFFER -DCATCHCHALLENGER_CLASS_STATS -DNOWEBSOCKET -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -I../stats -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang++ -o tinyxml2c.o ../../general/tinyXML2/tinyxml2c.cpp
"""
content = content.strip().split('\n')

MAX_CONCURRENCE = multiprocessing.cpu_count()+1

length = len(content)
for i in range(MAX_CONCURRENCE):
    t = Requester()
    t.start()

main_thread = threading.currentThread()
for t in threading.enumerate():
    if t is not main_thread:
        t.join()

if not has_success:
	sys.exit(123)

os.system("clang++ -ccc-gcc-name g++ -fsanitize=safe-stack -Wl,-z,relro -Wl,-z,now -Wl,-z,noexecstack -Wl,-z,separate-code -o stats main.o sha224.o LinkToLogin.o LinkToLoginProtocolParsing.o LinkToLoginStaticVar.o Epoll.o EpollSocket.o TinyXMLSettings.o FacilityLibGeneral.o cpp11addition.o cpp11additionstringtointc.o cpp11additionstringtointcpp.o ProtocolParsingCheck.o ProtocolParsingGeneral.o ProtocolParsingInput.o ProtocolParsingOutput.o EpollClient.o EpollUnixSocketServer.o EpollServerStats.o tinyxml2.o tinyxml2b.o tinyxml2c.o")
print('Finished')
