SOURCES += \
    $$PWD/base/GlobalServerData.cpp \
    $$PWD/base/PlayerUpdaterBase.cpp \
    $$PWD/base/SqlFunction.cpp \
    $$PWD/base/BaseServer/BaseServer.cpp \
    $$PWD/base/BaseServer/BaseServer2.cpp \
    $$PWD/base/BaseServer/BaseServer3.cpp \
    $$PWD/base/BaseServer/BaseServerSettings.cpp \
    $$PWD/base/BaseServer/BaseServerLoad.cpp \
    $$PWD/base/BaseServer/BaseServerLoadProfile.cpp \
    $$PWD/base/BaseServer/BaseServerLoadDatapack.cpp \
    $$PWD/base/BaseServer/BaseServerLoadOther.cpp \
    $$PWD/base/BaseServer/BaseServerLoadMap.cpp \
    $$PWD/base/BaseServer/BaseServerLoadMapAfterDB.cpp \
    $$PWD/base/BaseServer/BaseServerLoadSQL.cpp \
    $$PWD/base/BaseServer/BaseServerLoadSQLNotEpoll.cpp \
    $$PWD/base/BaseServer/BaseServerUnload.cpp \
    $$PWD/base/BaseServer/BaseServerMasterLoadDictionary.cpp \
    $$PWD/base/BaseServer/BaseServerMasterSendDatapack.cpp \
    $$PWD/base/BaseServer/BaseServerLogin.cpp \
    $$PWD/base/ClientEvents/LocalClientHandler.cpp \
    $$PWD/base/ClientEvents/LocalClientHandlerMove.cpp \
    $$PWD/base/ClientEvents/LocalClientHandlerReputation.cpp \
    $$PWD/base/ClientEvents/LocalClientHandlerFightManage.cpp \
    $$PWD/base/ClientEvents/LocalClientHandlerObject.cpp \
    $$PWD/base/ClientEvents/LocalClientHandlerWarehouse.cpp \
    $$PWD/base/ClientEvents/LocalClientHandlerCommand.cpp \
    $$PWD/base/ClientEvents/LocalClientHandlerDatabaseSync.cpp \
    $$PWD/base/ClientEvents/LocalClientHandlerShop.cpp \
    $$PWD/base/ClientEvents/LocalClientHandlerClan.cpp \
    $$PWD/base/ClientEvents/LocalClientHandlerCity.cpp \
    $$PWD/base/ClientEvents/LocalClientHandlerWithoutSender.cpp \
    $$PWD/base/ClientEvents/LocalClientHandlerQuest.cpp \
    $$PWD/base/ClientEvents/LocalClientHandlerTrade.cpp \
    $$PWD/base/ClientLocalBroadcast.cpp \
    $$PWD/base/Client.cpp \
    $$PWD/base/ClientStaticVar.cpp \
    $$PWD/base/ClientLoad/ClientHeavyLoad.cpp \
    $$PWD/base/ClientLoad/ClientHeavyLoadLogin.cpp \
    $$PWD/base/ClientLoad/ClientHeavyLoadLogin2.cpp \
    $$PWD/base/ClientLoad/ClientHeavyLoadMirror.cpp \
    $$PWD/base/ClientLoad/ClientHeavyLoadSelectChar.cpp \
    $$PWD/base/ClientLoad/ClientHeavyLoadSelectCharCommon.cpp \
    $$PWD/base/ClientLoad/ClientHeavyLoadSelectCharServer.cpp \
    $$PWD/base/ClientLoad/ClientHeavyLoadSelectCharFinal.cpp \
    $$PWD/base/ClientNetworkWrite.cpp \
    $$PWD/base/ClientNetworkRead.cpp \
    $$PWD/base/ClientNetworkReadMessage.cpp \
    $$PWD/base/ClientNetworkReadQuery.cpp \
    $$PWD/base/ClientNetworkReadWithoutSender.cpp \
    $$PWD/base/ClientBroadCast.cpp \
    $$PWD/base/MapServer.cpp \
    $$PWD/base/BroadCastWithoutSender.cpp \
    $$PWD/base/ClientMapManagement/ClientMapManagement.cpp \
    $$PWD/base/ClientMapManagement/MapVisibilityAlgorithm_WithoutSender.cpp \
    $$PWD/base/ClientMapManagement/MapVisibilityAlgorithm_None.cpp \
    $$PWD/base/ClientMapManagement/MapVisibilityAlgorithm_Simple_StoreOnSender.cpp \
    $$PWD/base/ClientMapManagement/MapVisibilityAlgorithm_WithBorder_StoreOnSender.cpp \
    $$PWD/base/ClientMapManagement/Map_server_MapVisibility_Simple_StoreOnSender.cpp \
    $$PWD/base/ClientMapManagement/Map_server_MapVisibility_WithBorder_StoreOnSender.cpp \
    $$PWD/base/ClientMapManagement/MapBasicMove.cpp \
    $$PWD/base/DictionaryLogin.cpp \
    $$PWD/base/DictionaryServer.cpp \
    $$PWD/base/PreparedDBQueryLogin.cpp \
    $$PWD/base/PreparedDBQueryCommon.cpp \
    $$PWD/base/PreparedDBQueryServer.cpp \
    $$PWD/base/DatabaseBase.cpp \
    $$PWD/base/TimeRangeEventScanBase.cpp \
    $$PWD/base/TinyXMLSettings.cpp \
    $$PWD/base/DatabaseFunction.cpp \
    $$PWD/base/StringWithReplacement.cpp \
    $$PWD/base/PreparedStatementUnit.cpp \
    $$PWD/crafting/BaseServerCrafting.cpp \
    $$PWD/crafting/ClientLocalBroadcastCrafting.cpp \
    $$PWD/crafting/LocalClientHandlerCrafting.cpp \
    $$PWD/crafting/ClientHeavyLoadCrafting.cpp \
    $$PWD/fight/LocalClientHandlerFight.cpp \
    $$PWD/fight/LocalClientHandlerFightSkill.cpp \
    $$PWD/fight/LocalClientHandlerFightBuff.cpp \
    $$PWD/fight/LocalClientHandlerFightWild.cpp \
    $$PWD/fight/LocalClientHandlerFightDatabase.cpp \
    $$PWD/fight/LocalClientHandlerFightBattle.cpp \
    $$PWD/fight/BaseServerFight.cpp \
    $$PWD/fight/ClientHeavyLoadFight.cpp
