TEMPLATE = app

DEFINES += TILED_ZLIB
LIBS += -lz

SOURCES += \
    $$PWD/base/GlobalServerData.cpp \
    $$PWD/base/SqlFunction.cpp \
    $$PWD/base/BaseServer.cpp \
    $$PWD/base/BaseServerSettings.cpp \
    $$PWD/base/BaseServerLoad.cpp \
    $$PWD/base/BaseServerLoadProfile.cpp \
    $$PWD/base/BaseServerLoadDatapack.cpp \
    $$PWD/base/BaseServerLoadOther.cpp \
    $$PWD/base/BaseServerLoadMap.cpp \
    $$PWD/base/BaseServerLoadMapAfterDB.cpp \
    $$PWD/base/BaseServerLoadBot.cpp \
    $$PWD/base/BaseServerLoadSQL.cpp \
    $$PWD/base/BaseServerLoadSQLNotEpoll.cpp \
    $$PWD/base/BaseServerLoadSQLPointAndMarket.cpp \
    $$PWD/base/BaseServerUnload.cpp \
    $$PWD/base/BaseServerMasterLoadDictionary.cpp \
    $$PWD/base/BaseServerMasterSendDatapack.cpp \
    $$PWD/base/LocalClientHandler.cpp \
    $$PWD/base/LocalClientHandlerMove.cpp \
    $$PWD/base/LocalClientHandlerReputation.cpp \
    $$PWD/base/LocalClientHandlerFightManage.cpp \
    $$PWD/base/LocalClientHandlerObject.cpp \
    $$PWD/base/LocalClientHandlerWarehouse.cpp \
    $$PWD/base/LocalClientHandlerCommand.cpp \
    $$PWD/base/LocalClientHandlerDatabaseSync.cpp \
    $$PWD/base/LocalClientHandlerIndustries.cpp \
    $$PWD/base/LocalClientHandlerShop.cpp \
    $$PWD/base/LocalClientHandlerClan.cpp \
    $$PWD/base/LocalClientHandlerMarket.cpp \
    $$PWD/base/LocalClientHandlerCity.cpp \
    $$PWD/base/LocalClientHandlerWithoutSender.cpp \
    $$PWD/base/LocalClientHandlerQuest.cpp \
    $$PWD/base/LocalClientHandlerTrade.cpp \
    $$PWD/base/ClientLocalBroadcast.cpp \
    $$PWD/base/EventThreader.cpp \
    $$PWD/base/Client.cpp \
    $$PWD/base/ClientStaticVar.cpp \
    $$PWD/base/ClientHeavyLoad.cpp \
    $$PWD/base/ClientHeavyLoadLogin.cpp \
    $$PWD/base/ClientHeavyLoadMirror.cpp \
    $$PWD/base/ClientHeavyLoadSelectChar.cpp \
    $$PWD/base/ClientHeavyLoadSelectCharCommon.cpp \
    $$PWD/base/ClientHeavyLoadSelectCharServer.cpp \
    $$PWD/base/ClientHeavyLoadSelectCharFinal.cpp \
    $$PWD/base/ClientNetworkWrite.cpp \
    $$PWD/base/ClientNetworkRead.cpp \
    $$PWD/base/ClientNetworkReadMessage.cpp \
    $$PWD/base/ClientNetworkReadQuery.cpp \
    $$PWD/base/ClientNetworkReadWithoutSender.cpp \
    $$PWD/base/ClientBroadCast.cpp \
    $$PWD/base/PlayerUpdater.cpp \
    $$PWD/base/MapServer.cpp \
    $$PWD/base/BroadCastWithoutSender.cpp \
    $$PWD/base/ClientMapManagement/ClientMapManagement.cpp \
    $$PWD/base/ClientMapManagement/MapVisibilityAlgorithm_WithoutSender.cpp \
    $$PWD/base/ClientMapManagement/MapVisibilityAlgorithm_None.cpp \
    $$PWD/base/ClientMapManagement/MapVisibilityAlgorithm_Simple_StoreOnSender.cpp \
    $$PWD/base/ClientMapManagement/MapVisibilityAlgorithm_WithBorder_StoreOnSender.cpp \
    $$PWD/base/ClientMapManagement/Map_server_MapVisibility_Simple_StoreOnSender.cpp \
    $$PWD/base/ClientMapManagement/Map_server_MapVisibility_WithBorder_StoreOnSender.cpp \
    $$PWD/base/ClientMapManagement/MapBasicMove.cpp \
    $$PWD/base/DictionaryLogin.cpp \
    $$PWD/base/DictionaryServer.cpp \
    $$PWD/base/PreparedDBQueryLogin.cpp \
    $$PWD/base/PreparedDBQueryCommon.cpp \
    $$PWD/base/PreparedDBQueryServer.cpp \
    $$PWD/base/DatabaseBase.cpp \
    $$PWD/base/BaseServerLogin.cpp \
    $$PWD/base/TinyXMLSettings.cpp \
    $$PWD/base/DatabaseFunction.cpp \
    $$PWD/base/StringWithReplacement.cpp \
    $$PWD/base/StaticText.cpp \
    $$PWD/base/PreparedStatementUnit.cpp \
    $$PWD/base/TimeRangeEventScan.cpp \
    $$PWD/crafting/BaseServerCrafting.cpp \
    $$PWD/crafting/ClientLocalBroadcastCrafting.cpp \
    $$PWD/crafting/LocalClientHandlerCrafting.cpp \
    $$PWD/crafting/ClientHeavyLoadCrafting.cpp \
    $$PWD/fight/LocalClientHandlerFight.cpp \
    $$PWD/fight/LocalClientHandlerFightSkill.cpp \
    $$PWD/fight/LocalClientHandlerFightBuff.cpp \
    $$PWD/fight/LocalClientHandlerFightWild.cpp \
    $$PWD/fight/LocalClientHandlerFightDatabase.cpp \
    $$PWD/fight/LocalClientHandlerFightBattle.cpp \
    $$PWD/fight/BaseServerFight.cpp \
    $$PWD/fight/ClientHeavyLoadFight.cpp \
    $$PWD/base/ClientWithSocket.cpp

HEADERS += \
    $$PWD/VariableServer.hpp \
    $$PWD/base/GlobalServerData.hpp \
    $$PWD/base/SqlFunction.hpp \
    $$PWD/base/BaseServer.hpp \
    $$PWD/base/BaseServerMasterLoadDictionary.hpp \
    $$PWD/base/BaseServerMasterSendDatapack.hpp \
    $$PWD/base/LocalClientHandlerWithoutSender.hpp \
    $$PWD/base/ServerStructures.hpp \
    $$PWD/base/EventThreader.hpp \
    $$PWD/base/Client.hpp \
    $$PWD/base/ClientNetworkReadWithoutSender.hpp \
    $$PWD/base/BroadCastWithoutSender.hpp \
    $$PWD/base/PlayerUpdater.hpp \
    $$PWD/base/MapServer.hpp \
    $$PWD/base/ClientMapManagement/ClientMapManagement.hpp \
    $$PWD/base/ClientMapManagement/MapVisibilityAlgorithm_WithoutSender.hpp \
    $$PWD/base/ClientMapManagement/MapVisibilityAlgorithm_None.hpp \
    $$PWD/base/ClientMapManagement/MapVisibilityAlgorithm_Simple_StoreOnSender.hpp \
    $$PWD/base/ClientMapManagement/MapVisibilityAlgorithm_WithBorder_StoreOnSender.hpp \
    $$PWD/base/ClientMapManagement/Map_server_MapVisibility_Simple_StoreOnSender.hpp \
    $$PWD/base/ClientMapManagement/Map_server_MapVisibility_WithBorder_StoreOnSender.hpp \
    $$PWD/base/ClientMapManagement/MapBasicMove.hpp \
    $$PWD/base/DictionaryLogin.hpp \
    $$PWD/base/DictionaryServer.hpp \
    $$PWD/base/PreparedDBQuery.hpp \
    $$PWD/base/DatabaseBase.hpp \
    $$PWD/base/BaseServerLogin.hpp \
    $$PWD/base/TinyXMLSettings.hpp \
    $$PWD/base/DatabaseFunction.hpp \
    $$PWD/base/StringWithReplacement.hpp \
    $$PWD/base/StaticText.hpp \
    $$PWD/base/GameServerVariables.hpp \
    $$PWD/base/PreparedStatementUnit.hpp \
    $$PWD/base/TimeRangeEventScan.hpp \
    $$PWD/crafting/MapServerCrafting.hpp \
    $$PWD/base/ClientWithSocket.hpp
