#ifndef VARIABLESERVER_H
#define VARIABLESERVER_H

//#define DEBUG_MESSAGE_CLIENT_COMPLEXITY_LINEARE
//#define DEBUG_MESSAGE_CLIENT_COMPLEXITY_SQUARE
//#define DEBUG_MESSAGE_CLIENT_MOVE
//#define DEBUG_MESSAGE_CLIENT_RAW_NETWORK
//#define DEBUG_MESSAGE_CLIENT_RAW_MAP

//in ms
#define POKECRAFT_SERVER_TIME_TO_SEND_MOVEMENT 50
#define POKECRAFT_SERVER_NORMAL_SPEED 200

#define POKECRAFT_SERVER_RANDOM_LIST_SIZE 512

#define POKECRAFT_SERVER_EXTRA_CHECK

#endif // VARIABLESERVER_H
