#ifndef CATCHCHALLENGER_QTOPENGL_DISPLAY_STRUCTURES_H
#define CATCHCHALLENGER_QTOPENGL_DISPLAY_STRUCTURES_H

#include "../libqtcatchchallenger/DisplayStructures.hpp"

#endif // CATCHCHALLENGER_QTOPENGL_DISPLAY_STRUCTURES_H
