#ifndef CATCHCHALLENGER_VARIABLESERVER_H
#define CATCHCHALLENGER_VARIABLESERVER_H

/*
#define DEBUG_MESSAGE_CLIENT_SQL
#define DEBUG_MESSAGE_CLIENT_COMPLEXITY_LINEARE
#define CATCHCHALLENGER_DEBUG_FIGHT
#define CATCHCHALLENGER_DEBUG_FIGHT_BOT
#define DEBUG_MESSAGE_CLIENT_QUESTS
#define DEBUG_MESSAGE_CLIENT_REPUTATION
#define DEBUG_MESSAGE_CLIENT_MOVE
#define DEBUG_MESSAGE_CLIENT_COMPLEXITY_SQUARE
//*/

/*
#define DEBUG_MESSAGE_CLIENT_RAW_NETWORK
#define DEBUG_MESSAGE_MAP_LOAD
#define DEBUG_MESSAGE_MAP_PLANTS
#define DEBUG_MESSAGE_BUFF_LOAD
#define DEBUG_MESSAGE_SKILL_LOAD
#define DEBUG_MESSAGE_MONSTER_XP_LOAD
#define DEBUG_MESSAGE_MONSTER_LOAD
//*/

//in ms
#define CATCHCHALLENGER_SERVER_MAP_TIME_TO_SEND_MOVEMENT 150
#define CATCHCHALLENGER_SERVER_NORMAL_SPEED 250 //then 250ms, see the protocol
#define CATCHCHALLENGER_SERVER_DDOS_MAX_VALUE 6

#define CATCHCHALLENGER_SERVER_MAXNOTLOGGEDCONNECTION 50 //smaller = more performance, but less simmulaneous connexion try, this number * (CATCHCHALLENGER_TOKENSIZE_CONNECTGAMESERVER+pointer)
#define CATCHCHALLENGER_SERVER_OWNER_TIMEOUT 60*60*24

//#define CATCHCHALLENGER_SERVER_DATAPACK_ONLYBYMIRROR
#ifndef CATCHCHALLENGER_SERVER_DATAPACK_ONLYBYMIRROR
#define CATCHCHALLENGER_SERVER_DATAPACK_MIN_FILEPURGE_KB 100
#define CATCHCHALLENGER_SERVER_DATAPACK_MAX_FILEPURGE_KB 400
#define CATCHCHALLENGER_SERVER_DATAPACK_LZ4_COMPRESSEDFILEPURGE_KB 600
#define CATCHCHALLENGER_SERVER_DATAPACK_ZLIB_COMPRESSEDFILEPURGE_KB 600
#define CATCHCHALLENGER_SERVER_DATAPACK_XZ_COMPRESSEDFILEPURGE_KB 3000
#define CATCHCHALLENGER_SERVER_DATAPACK_DONT_COMPRESS_GREATER_THAN_KB 8000
#endif

#define CATCHCHALLENGER_EXTENSION_COMPRESSED "tmx;xml;tsx;js"

#define RANDOMFILEDEVICE "/dev/urandom"

//put for map, add for local thread
//put this size into the options
#define CATCHCHALLENGER_SERVER_RANDOM_INTERNAL_SIZE 4096
#define CATCHCHALLENGER_SERVER_RANDOM_LIST_SIZE 255 // not 256 to don't add 00 into size header
#define CATCHCHALLENGER_SERVER_MIN_RANDOM_LIST_SIZE 32

/// check more, then use more cpu, it's to develop and detect the internal bug
//#define CATCHCHALLENGER_SERVER_EXTRA_CHECK

#define CATCHCHALLENGER_GAMESERVER_EVENTSTARTONLOCALTIME

#ifdef CATCHCHALLENGER_CLASS_ONLYGAMESERVER
//disable this if in cluster mode with all login server with DDOS
#define CATCHCHALLENGER_DDOS_FILTER
#else
#define CATCHCHALLENGER_DDOS_FILTER
#endif

#if defined(CATCHCHALLENGER_SERVER) || defined(CATCHCHALLENGER_CLASS_ONLYGAMESERVER)
    #ifdef CATCHCHALLENGER_DB_POSTGRESQL
        #define CATCHCHALLENGERDEFAULTDBTYPE "postgresql"
    #else
        #ifdef CATCHCHALLENGER_DB_MYSQL
            #define CATCHCHALLENGERDEFAULTDBTYPE "mysql"
        #else
            //CATCHCHALLENGER_CLASS_QT
            #ifdef CATCHCHALLENGER_CLIENT
                #define CATCHCHALLENGERDEFAULTDBTYPE "sqlite"
            #else
                #define CATCHCHALLENGERDEFAULTDBTYPE "mysql"
            #endif
        #endif
    #endif
#else
    #define CATCHCHALLENGERDEFAULTDBTYPE "sqlite"
#endif

#endif // VARIABLESERVER_H
