#ifndef CATCHCHALLENGER_CLIENTVARIABLE_H
#define CATCHCHALLENGER_CLIENTVARIABLE_H

/*
#define DEBUG_BASEWINDOWS
#define DEBUG_RENDER_CACHE
*/
#define DEBUG_CLIENT_LOAD_ORDER
#define DEBUG_CLIENT_PLAYER_ON_MAP
//#define DEBUG_CLIENT_QUEST
//#define DEBUG_CLIENT_OTHER_PLAYER_MOVE_STEP
#define DEBUG_CLIENT_BATTLE

#define TIMETODISPLAY_TIP 8000
#define TIMETODISPLAY_GAIN 8000

#endif // CATCHCHALLENGER_CLIENTVARIABLE_H
