#ifndef POKECRAFT_CLIENTVARIABLE_H
#define POKECRAFT_CLIENTVARIABLE_H

/*
#define DEBUG_BASEWINDOWS
#define DEBUG_RENDER_CACHE
*/
#define DEBUG_CLIENT_PLAYER_ON_MAP
#define DEBUG_CLIENT_LOAD_ORDER
//#define DEBUG_CLIENT_OTHER_PLAYER_MOVE_STEP

#endif // POKECRAFT_CLIENTVARIABLE_H
