#ifndef CATCHCHALLENGER_CLIENTVARIABLE_H
#define CATCHCHALLENGER_CLIENTVARIABLE_H

//#define DEBUG_BASEWINDOWS
//#define DEBUG_RENDER_CACHE
//#define DEBUG_RENDER_DISPLAY_INDIVIDUAL_LAYER
#define DEBUG_CLIENT_LOAD_ORDER
#define DEBUG_CLIENT_PLAYER_ON_MAP
//#define DEBUG_CLIENT_QUEST
//#define DEBUG_CLIENT_OTHER_PLAYER_MOVE_STEP
#define DEBUG_CLIENT_BATTLE
#define DEBUG_CLIENT_BOT
#define DEBUG_CLIENT_NETWORK_USAGE

#define TIMETODISPLAY_TIP 8000
#define TIMETODISPLAY_GAIN 8000

#define CLIENT_BASE_TILE_SIZE 16

#endif // CATCHCHALLENGER_CLIENTVARIABLE_H
