import threading
import subprocess
import os
import sys
import multiprocessing
import logging

iterator = -1
logging.basicConfig(level=logging.DEBUG, format='(%(threadName)-9s) %(message)s',)

class Requester(threading.Thread):
    def __init__(self):
        threading.Thread.__init__(self)
        self.lock = threading.Lock()

    def run(self):
        global iterator, content, length
        while True:
            self.lock.acquire()
            iterator = iterator + 1
            if iterator < length:
                command = content[iterator]
            else:
                command = None
            self.lock.release()
            if command is None:
                break
            elif len(command) > 0:
                parts = command.strip().split(' ')
                try:
                    output = subprocess.run(parts, stdout=subprocess.PIPE, check=True)
                    if output.returncode != 0:
                        logging.error(output.stderr)
                except Exception as err:
                    logging.error('command: ' + command + ' exception: ' + str(err))

content = """
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o CompressionProtocol.o ../../general/base/CompressionProtocol.cpp
clang -c -pipe -fstack-protector-all -g -fno-rtti -O2 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o debug.o ../../general/libzstd/lib/common/debug.c
clang -c -pipe -fstack-protector-all -g -fno-rtti -O2 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o entropy_common.o ../../general/libzstd/lib/common/entropy_common.c
clang -c -pipe -fstack-protector-all -g -fno-rtti -O2 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o error_private.o ../../general/libzstd/lib/common/error_private.c
clang -c -pipe -fstack-protector-all -g -fno-rtti -O2 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o fse_decompress.o ../../general/libzstd/lib/common/fse_decompress.c
clang -c -pipe -fstack-protector-all -g -fno-rtti -O2 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o pool.o ../../general/libzstd/lib/common/pool.c
clang -c -pipe -fstack-protector-all -g -fno-rtti -O2 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o threading.o ../../general/libzstd/lib/common/threading.c
clang -c -pipe -fstack-protector-all -g -fno-rtti -O2 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o xxbhash.o ../../general/libzstd/lib/common/xxbhash.c
clang -c -pipe -fstack-protector-all -g -fno-rtti -O2 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o zstd_common.o ../../general/libzstd/lib/common/zstd_common.c
clang -c -pipe -fstack-protector-all -g -fno-rtti -O2 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o fse_compress.o ../../general/libzstd/lib/compress/fse_compress.c
clang -c -pipe -fstack-protector-all -g -fno-rtti -O2 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o hist.o ../../general/libzstd/lib/compress/hist.c
clang -c -pipe -fstack-protector-all -g -fno-rtti -O2 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o huf_compress.o ../../general/libzstd/lib/compress/huf_compress.c
clang -c -pipe -fstack-protector-all -g -fno-rtti -O2 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o zstd_compress.o ../../general/libzstd/lib/compress/zstd_compress.c
clang -c -pipe -fstack-protector-all -g -fno-rtti -O2 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o zstd_compress_literals.o ../../general/libzstd/lib/compress/zstd_compress_literals.c
clang -c -pipe -fstack-protector-all -g -fno-rtti -O2 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o zstd_compress_sequences.o ../../general/libzstd/lib/compress/zstd_compress_sequences.c
clang -c -pipe -fstack-protector-all -g -fno-rtti -O2 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o zstd_compress_superblock.o ../../general/libzstd/lib/compress/zstd_compress_superblock.c
clang -c -pipe -fstack-protector-all -g -fno-rtti -O2 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o zstd_double_fast.o ../../general/libzstd/lib/compress/zstd_double_fast.c
clang -c -pipe -fstack-protector-all -g -fno-rtti -O2 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o zstd_fast.o ../../general/libzstd/lib/compress/zstd_fast.c
clang -c -pipe -fstack-protector-all -g -fno-rtti -O2 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o zstd_lazy.o ../../general/libzstd/lib/compress/zstd_lazy.c
clang -c -pipe -fstack-protector-all -g -fno-rtti -O2 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o zstd_ldm.o ../../general/libzstd/lib/compress/zstd_ldm.c
clang -c -pipe -fstack-protector-all -g -fno-rtti -O2 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o zstd_opt.o ../../general/libzstd/lib/compress/zstd_opt.c
clang -c -pipe -fstack-protector-all -g -fno-rtti -O2 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o zstdmt_compress.o ../../general/libzstd/lib/compress/zstdmt_compress.c
clang -c -pipe -fstack-protector-all -g -fno-rtti -O2 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o huf_decompress.o ../../general/libzstd/lib/decompress/huf_decompress.c
clang -c -pipe -fstack-protector-all -g -fno-rtti -O2 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o zstd_ddict.o ../../general/libzstd/lib/decompress/zstd_ddict.c
clang -c -pipe -fstack-protector-all -g -fno-rtti -O2 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o zstd_decompress.o ../../general/libzstd/lib/decompress/zstd_decompress.c
clang -c -pipe -fstack-protector-all -g -fno-rtti -O2 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o zstd_decompress_block.o ../../general/libzstd/lib/decompress/zstd_decompress_block.c
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o sha224.o ../../general/sha224/sha224.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o main-epoll-login-slave.o ../login/main-epoll-login-slave.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o EpollClientLoginSlave.o ../login/EpollClientLoginSlave.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o EpollServerLoginSlave.o ../login/EpollServerLoginSlave.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o EpollClientLoginSlaveStaticVar.o ../login/EpollClientLoginSlaveStaticVar.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o EpollClientLoginSlaveHeavyLoad.o ../login/EpollClientLoginSlaveHeavyLoad.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o LinkToMaster.o ../login/LinkToMaster.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o LinkToMasterStaticVar.o ../login/LinkToMasterStaticVar.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o LinkToMasterProtocolParsing.o ../login/LinkToMasterProtocolParsing.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o LinkToMasterProtocolParsingMessage.o ../login/LinkToMasterProtocolParsingMessage.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o LinkToMasterProtocolParsingReply.o ../login/LinkToMasterProtocolParsingReply.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o EpollClientLoginSlaveProtocolParsing.o ../login/EpollClientLoginSlaveProtocolParsing.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o EpollClientLoginSlaveWrite.o ../login/EpollClientLoginSlaveWrite.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o CharactersGroupForLogin.o ../login/CharactersGroupForLogin.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o CharactersGroupClient.o ../login/CharactersGroupClient.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o LinkToGameServerStaticVar.o ../login/LinkToGameServerStaticVar.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o LinkToGameServerProtocolParsing.o ../login/LinkToGameServerProtocolParsing.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o LinkToGameServer.o ../login/LinkToGameServer.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o TimerDdos.o ../login/TimerDdos.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o Epoll.o ../epoll/Epoll.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o EpollGenericSslServer.o ../epoll/EpollGenericSslServer.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o EpollGenericServer.o ../epoll/EpollGenericServer.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o EpollClient.o ../epoll/EpollClient.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o EpollSocket.o ../epoll/EpollSocket.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o EpollSslClient.o ../epoll/EpollSslClient.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o EpollPostgresql.o ../epoll/db/EpollPostgresql.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o EpollClientToServer.o ../epoll/EpollClientToServer.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o EpollSslClientToServer.o ../epoll/EpollSslClientToServer.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o EpollTimer.o ../epoll/EpollTimer.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o ProtocolParsingCheck.o ../../general/base/ProtocolParsingCheck.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o ProtocolParsingGeneral.o ../../general/base/ProtocolParsingGeneral.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o ProtocolParsingInput.o ../../general/base/ProtocolParsingInput.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o ProtocolParsingOutput.o ../../general/base/ProtocolParsingOutput.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o FacilityLibGeneral.o ../../general/base/FacilityLibGeneral.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o CommonSettingsCommon.o ../../general/base/CommonSettingsCommon.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o cpp11addition.o ../../general/base/cpp11addition.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o cpp11additionstringtointc.o ../../general/base/cpp11additionstringtointc.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o cpp11additionstringtointcpp.o ../../general/base/cpp11additionstringtointcpp.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o DatabaseBase.o ../base/DatabaseBase.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o PreparedDBQueryLogin.o ../base/PreparedDBQueryLogin.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o PreparedDBQueryCommon.o ../base/PreparedDBQueryCommon.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o PreparedDBQueryServer.o ../base/PreparedDBQueryServer.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o PreparedStatementUnit.o ../base/PreparedStatementUnit.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o BaseServerLogin.o ../base/BaseServerLogin.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o SqlFunction.o ../base/SqlFunction.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o DictionaryLogin.o ../base/DictionaryLogin.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o TinyXMLSettings.o ../base/TinyXMLSettings.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o DatabaseFunction.o ../base/DatabaseFunction.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o StringWithReplacement.o ../base/StringWithReplacement.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o TimerDetectTimeout.o ../login/TimerDetectTimeout.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o Version.o ../../general/base/Version.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o tinyxml2.o ../../general/tinyXML2/tinyxml2.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o tinyxml2b.o ../../general/tinyXML2/tinyxml2b.cpp
clang++ -c -pipe -fstack-protector-all -std=c++0x -g -fno-rtti -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DTIXML_USE_STL -DEPOLLCATCHCHALLENGERSERVER -DQT_NO_EMIT -DCATCHCHALLENGER_CLASS_LOGIN -DCATCHCHALLENGER_DB_POSTGRESQL -DCATCHCHALLENGER_DB_PREPAREDSTATEMENT -DCATCHCHALLENGER_XLMPARSER_TINYXML2 -DQT_NO_DEBUG -I../login -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -o tinyxml2c.o ../../general/tinyXML2/tinyxml2c.cpp
"""
content = content.strip().split('\n')

MAX_CONCURRENCE = multiprocessing.cpu_count()+1

length = len(content)
for i in range(MAX_CONCURRENCE):
    t = Requester()
    t.start()

main_thread = threading.currentThread()
for t in threading.enumerate():
    if t is not main_thread:
        t.join()

os.system("clang++ -ccc-gcc-name g++ -o catchchallenger-server-login CompressionProtocol.o debug.o entropy_common.o error_private.o fse_decompress.o pool.o threading.o xxbhash.o zstd_common.o fse_compress.o hist.o huf_compress.o zstd_compress.o zstd_compress_literals.o zstd_compress_sequences.o zstd_compress_superblock.o zstd_double_fast.o zstd_fast.o zstd_lazy.o zstd_ldm.o zstd_opt.o zstdmt_compress.o huf_decompress.o zstd_ddict.o zstd_decompress.o zstd_decompress_block.o sha224.o main-epoll-login-slave.o EpollClientLoginSlave.o EpollServerLoginSlave.o EpollClientLoginSlaveStaticVar.o EpollClientLoginSlaveHeavyLoad.o LinkToMaster.o LinkToMasterStaticVar.o LinkToMasterProtocolParsing.o LinkToMasterProtocolParsingMessage.o LinkToMasterProtocolParsingReply.o EpollClientLoginSlaveProtocolParsing.o EpollClientLoginSlaveWrite.o CharactersGroupForLogin.o CharactersGroupClient.o LinkToGameServerStaticVar.o LinkToGameServerProtocolParsing.o LinkToGameServer.o TimerDdos.o Epoll.o EpollGenericSslServer.o EpollGenericServer.o EpollClient.o EpollSocket.o EpollSslClient.o EpollPostgresql.o EpollClientToServer.o EpollSslClientToServer.o EpollTimer.o ProtocolParsingCheck.o ProtocolParsingGeneral.o ProtocolParsingInput.o ProtocolParsingOutput.o FacilityLibGeneral.o CommonSettingsCommon.o cpp11addition.o cpp11additionstringtointc.o cpp11additionstringtointcpp.o DatabaseBase.o PreparedDBQueryLogin.o PreparedDBQueryCommon.o PreparedDBQueryServer.o PreparedStatementUnit.o BaseServerLogin.o SqlFunction.o DictionaryLogin.o TinyXMLSettings.o DatabaseFunction.o StringWithReplacement.o TimerDetectTimeout.o Version.o tinyxml2.o tinyxml2b.o tinyxml2c.o   -lpq")
print('Finished')
