#ifndef CATCHCHALLENGER_VARIABLELOGINSERVER_H
#define CATCHCHALLENGER_VARIABLELOGINSERVER_H

#define DEBUG_MESSAGE_QUERY_IDLIST
//#define CATCHCHALLENGER_DEBUG_SERVERLIST

#endif // VARIABLELOGINSERVER_H
